name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test secret exists
        run: |
            if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "Secret is EMPTY"
            else
            echo "Secret is AVAILABLE"
            fi

      - name: Check database secret presence
        run: |
            if [ -z "${{ secrets.DATABASE_PASSWORD }}" ]; then
            echo "DATABASE_PASSWORD is EMPTY"
            else
            echo "DATABASE_PASSWORD exists"
            fi
      - name: Dump secret length
        run: |
            echo "Length = ${#DATABASE_PASSWORD}"